import {describe, it, expect} from 'vitest';
import {InMemoryWorkflowRepository, PostgresWorkflowRepository} from './index';

describe('workflow repository contract', () => {
  it('stores and returns an isolated workflow snapshot', async () => { const repository = new InMemoryWorkflowRepository(); await repository.save({requestId: 'r', customerId: 'CUST-1042', status: 'approval', planHash: 'h', createdAt: 'now'}); const workflow = await repository.get('r'); expect(workflow?.customerId).toBe('CUST-1042'); expect(workflow).not.toBe(await repository.get('missing')); });
  it('clears in-memory metadata without affecting unrelated data', async () => { const repository = new InMemoryWorkflowRepository(); await repository.save({requestId: 'r', customerId: 'CUST-1042', status: 'approval', planHash: 'h', createdAt: 'now'}); await repository.clear(); expect(await repository.get('r')).toBeUndefined(); });
  it('uses a transaction and parameterized SQL', async () => { const calls: string[] = []; const repository = new PostgresWorkflowRepository({query: async sql => { calls.push(sql); return {rows: []}; }}); await repository.save({requestId: 'r', customerId: 'CUST-1042', status: 'approval', planHash: 'h', createdAt: 'now'}); expect(calls[0]).toBe('BEGIN'); expect(calls.some(sql => sql.includes('$1'))).toBe(true); expect(calls.some(sql => sql.includes('canonical'))).toBe(true); expect(calls.at(-1)).toBe('COMMIT'); });
  it('rolls back when persistence fails', async () => { const calls: string[] = []; const repository = new PostgresWorkflowRepository({query: async sql => { calls.push(sql); if (sql.startsWith('INSERT')) throw new Error('db unavailable'); return {rows: []}; }}); await expect(repository.save({requestId: 'r', customerId: 'CUST-1042', status: 'approval', planHash: 'h', createdAt: 'now'})).rejects.toThrow('db unavailable'); expect(calls).toContain('ROLLBACK'); });
  it('clears persisted workflow metadata transactionally', async () => { const calls: string[] = []; const repository = new PostgresWorkflowRepository({query: async sql => { calls.push(sql); return {rows: []}; }}); await repository.clear(); expect(calls).toEqual(['BEGIN', 'DELETE FROM eraseops_execution_results', 'DELETE FROM eraseops_approvals', 'DELETE FROM eraseops_plans', 'DELETE FROM eraseops_requests', 'COMMIT']); });
});
