import {useMemo, useState} from 'react';
import {ShieldCheck, Search, ArrowUpRight, CheckCircle2, CircleAlert, Database, Box, LockKeyhole, Download} from 'lucide-react';
import {useWorkflowStore} from './store';
import {parseCommand} from './command-parser';
import {DataVisuals} from './components/DataVisuals';

type AnyRecord=Record<string,any>;
const stages=['intake','discovery','footprint','dependencies','classification','plan','sandbox','backup','blast_radius','policy','approval','execution','rescan','report'];
const tabs=['overview','footprint','dependencies','plan','audit'];

async function json(response:Response){const body=await response.json() as AnyRecord;if(!response.ok)throw new Error(body.error??`Request failed (${response.status})`);return body}

export default function App(){
  const workflow=useWorkflowStore(s=>s.workflow) as AnyRecord|undefined; const setWorkflow=useWorkflowStore(s=>s.setWorkflow);
  const [customerId,setCustomerId]=useState(''); const [command,setCommand]=useState(''); const [tab,setTab]=useState('overview'); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const request=async(id=customerId)=>{if(!/^CUST-\d{4}$/.test(id)){setError('Enter a valid customer ID such as CUST-1234');return}setBusy(true);setError('');try{setWorkflow(await json(await fetch('/api/requests',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({customerId:id,reason:'Customer erasure request',dryRun:false})})))}catch(e){setError(e instanceof Error?e.message:'Unable to create request')}finally{setBusy(false)}};
  const action=async(path:string,body:AnyRecord={})=>{if(!workflow)return;setBusy(true);setError('');try{setWorkflow(await json(await fetch(`/api/requests/${workflow.requestId}/${path}`,{method:'POST',headers:{'content-type':'application/json','x-operator-identity':'operator'},body:JSON.stringify(body)})))}catch(e){setError(e instanceof Error?e.message:'Action failed')}finally{setBusy(false)}};
  const runCommand=async()=>{const intent=parseCommand(command);setCommand('');if(intent.kind==='request'&&intent.customerId)return request(intent.customerId);if(intent.kind==='approve'&&workflow?.stage==='approval')return action('approve',{confirmation:workflow.customerId});if(intent.kind==='reject'&&workflow?.stage==='approval')return action('reject');if(intent.kind==='blocked'){setError('Destructive execution requires an approved plan and explicit human authorization.');return}setError('Try: discover customer CUST-1234, show blast radius, verify deletion, or generate audit report.')};
  if(!workflow)return <main className="fresh-shell"><Header/><section className="welcome"><div className="welcome-copy"><div className="kicker"><span className="pulse"/> ERASURE CONTROL PLANE / DEMO SANDBOX</div><h1>Deletion with<br/><em>evidence.</em></h1><p>Discover personal data across connected systems, prove the plan is safe, and require a human checkpoint before anything destructive happens.</p></div><form className="start-card" onSubmit={e=>{e.preventDefault();void request()}}><div className="kicker">NEW ERASURE REQUEST</div><label htmlFor="customer">CUSTOMER IDENTIFIER</label><div className="input-row"><input id="customer" value={customerId} onChange={e=>setCustomerId(e.target.value.toUpperCase())} placeholder="CUST-1234" autoFocus/><button disabled={busy}>{busy?'SCANNING':'DISCOVER'} <ArrowUpRight size={16}/></button></div><small>Discovery is read-only. The approval gate is required before destructive execution.</small></form></section><section className="principles"><Principle icon={<Search/>} title="Discover" text="Scan configured PostgreSQL and object-storage connectors."/><Principle icon={<ShieldCheck/>} title="Verify" text="Hash the plan, test dependencies, and validate backups."/><Principle icon={<LockKeyhole/>} title="Approve" text="Keep irreversible actions behind an explicit checkpoint."/></section>{error&&<div className="fresh-error">{error}</div>}</main>;
  const activeStage=stages.indexOf(workflow.stage); const assets=workflow.assets??[]; const actions=workflow.plan?.items??[]; const systems=[...new Set(assets.map((a:AnyRecord)=>a.system))];
  return <main className="fresh-shell"><Header customer={workflow.customerId}/><section className="topbar"><div><div className="kicker">ACTIVE REQUEST</div><h2>{workflow.customerId}<span> / {workflow.status.replace('_',' ')}</span></h2></div><div className="top-actions"><input value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void runCommand()}} placeholder="Ask EraseOps…"/><button onClick={()=>void runCommand()}><Search size={15}/></button></div></section><section className="stagebar">{stages.map((stage,i)=><div className={`${i<=activeStage?'done ':''}${stage===workflow.stage?'current':''}`} key={stage}><b>{String(i+1).padStart(2,'0')}</b><span>{stage.replace('_',' ')}</span></div>)}</section><section className="summary-grid"><Summary label="SYSTEMS SCANNED" value={systems.length} icon={<Database/>}/><Summary label="ASSETS FOUND" value={assets.length} icon={<Box/>}/><Summary label="TO DELETE" value={workflow.blastRadius.deletable} tone="teal"/><Summary label="TO ANONYMIZE" value={workflow.blastRadius.anonymized} tone="gold"/><Summary label="PLAN RISK" value={workflow.sandbox?.status==='failed'?'BLOCKED':workflow.blastRadius.deletable>10?'HIGH':'REVIEW'} tone={workflow.sandbox?.status==='failed'?'red':'gold'}/></section><div className="work-grid"><section className="workspace"><nav className="tabs">{tabs.map(item=><button className={tab===item?'selected':''} onClick={()=>setTab(item)} key={item}>{item}</button>)}</nav>{tab==='overview'&&<Overview workflow={workflow} assets={assets}/>} {tab==='footprint'&&<Footprint assets={assets}/>} {tab==='dependencies'&&<DataVisuals workflow={workflow}/>} {tab==='plan'&&<Plan items={actions} hash={workflow.plan?.hash}/>} {tab==='audit'&&<Audit events={workflow.events}/>}</section><aside className="guard-card"><div className="guard-head"><div><div className="kicker">SAFETY GATE</div><h3>Human checkpoint</h3></div><ShieldCheck size={24}/></div><p>Execution stays locked until the sandbox, backup, policy, and exact plan hash all pass.</p><Gate label="Sandbox verification" ok={workflow.sandbox?.status==='passed'}/><Gate label="Backup integrity" ok={workflow.backupVerified}/><Gate label="Plan hash bound" ok={Boolean(workflow.plan?.hash)}/>{workflow.sandbox?.failures?.length>0&&<div className="danger-box"><CircleAlert size={16}/><span>{workflow.sandbox.failures[0]}</span></div>}{workflow.stage==='approval'&&<Approval workflow={workflow} busy={busy} action={action}/>} {workflow.stage==='execution'&&<button className="execute" disabled={busy} onClick={()=>void action('execute-guarded',{approvalId:workflow.approval?.token,planHash:workflow.plan.hash})}>Confirm guarded execution <ArrowUpRight size={15}/></button>}{workflow.stage==='report'&&<div className="success-box"><CheckCircle2 size={16}/> Verification complete</div>}</aside></div>{error&&<div className="fresh-error">{error}</div>}</main>;
}
function Header({customer}:{customer?:string}){return <header className="fresh-header"><div className="brand-mark">⌁</div><div><div className="kicker">ERASEOPS</div><strong>AUTONOMOUS DATA DELETION</strong></div><div className="header-right"><span className="status-dot"/> DEMO SANDBOX {customer&&<b>{customer}</b>}</div></header>}
function Principle({icon,title,text}:{icon:any;title:string;text:string}){return <article><span>{icon}</span><h3>{title}</h3><p>{text}</p></article>}
function Summary({label,value,icon,tone}:{label:string;value:any;icon?:any;tone?:string}){return <div className="summary"><div className="kicker">{label}</div><strong className={tone}>{value}</strong>{icon&&<span>{icon}</span>}</div>}
function Overview({workflow,assets}:{workflow:AnyRecord;assets:AnyRecord[]}){return <div className="overview"><div className="section-title"><div><div className="kicker">MISSION CONTROL</div><h3>What is happening now</h3></div><span className="stage-pill">{workflow.stage.replace('_',' ')}</span></div><div className="activity-list">{workflow.events?.slice().reverse().map((event:AnyRecord)=><div key={event.id}><i/><div><strong>{event.message}</strong><small>{event.stage} · {new Date(event.at).toLocaleTimeString()}</small></div></div>)}</div><div className="recent-assets"><div className="kicker">LATEST DISCOVERED ASSETS</div>{assets.slice(0,5).map(asset=><div key={asset.id}><span className={'asset-dot '+asset.classification}/><strong>{asset.label}</strong><small>{asset.system} / {asset.table} · {asset.count}</small></div>)}</div></div>}
function Footprint({assets}:{assets:AnyRecord[]}){return <div className="data-table"><div className="section-title"><div><div className="kicker">DATA FOOTPRINT</div><h3>Discovered resources</h3></div></div><div className="table-head"><span>RESOURCE</span><span>SYSTEM</span><span>COUNT</span><span>CLASSIFICATION</span></div>{assets.map(a=><div className="table-row" key={a.id}><strong>{a.label}<small>{a.table}</small></strong><span>{a.system}</span><span>{a.count}</span><b className={a.classification}>{a.classification}</b></div>)}</div>}
function Plan({items,hash}:{items:AnyRecord[];hash?:string}){return <div className="data-table"><div className="section-title"><div><div className="kicker">DETERMINISTIC PLAN</div><h3>Proposed actions</h3></div><code>{hash?.slice(0,18)}…</code></div>{items.map((item,index)=><div className="plan-row" key={item.id}><b>{String(index+1).padStart(2,'0')}</b><strong>{item.action.toUpperCase()} · {item.label}<small>{item.system} / {item.table} · {item.count} records · {item.risk} risk</small></strong><span className={item.action}>{item.action}</span></div>)}</div>}
function Audit({events}:{events:AnyRecord[]}){return <div className="data-table"><div className="section-title"><div><div className="kicker">APPEND-ONLY RECORD</div><h3>Audit trail</h3></div><button className="icon-button" onClick={()=>{const blob=new Blob([JSON.stringify(events,null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='eraseops-audit.json';link.click()}}><Download size={15}/></button></div>{events?.slice().reverse().map(e=><div className="audit-row" key={e.id}><i/><div><strong>{e.message}</strong><small>{e.stage} · {new Date(e.at).toLocaleString()}</small></div></div>)}</div>}
function Gate({label,ok}:{label:string;ok:boolean}){return <div className="gate"><span className={ok?'ok':'pending'}>{ok?'✓':'·'}</span><strong>{label}</strong><small>{ok?'PASS':'PENDING'}</small></div>}
function Approval({workflow,busy,action}:{workflow:AnyRecord;busy:boolean;action:(path:string,body?:AnyRecord)=>Promise<void>}){const [value,setValue]=useState('');return <div className="approval"><div className="kicker">IRREVERSIBLE OPERATION</div><p>Type <b>{workflow.customerId}</b> to authorize this exact plan.</p><input value={value} onChange={e=>setValue(e.target.value.toUpperCase())} placeholder={workflow.customerId}/><button className="approve" disabled={busy||value!==workflow.customerId} onClick={()=>void action('approve',{confirmation:value})}>Approve exact plan</button><button className="reject" disabled={busy} onClick={()=>void action('reject')}>Reject plan</button></div>}
