import {useState} from 'react';
import {ArrowRight, Check, Database, FileCheck2, Menu, Network, ShieldCheck, Terminal, UserCheck, X, type LucideIcon} from 'lucide-react';
import {Link} from 'react-router-dom';

const steps = [
  ['01', 'Discover', 'Find customer data across connected systems.'],
  ['02', 'Map', 'Trace ownership, foreign keys, and shared dependencies.'],
  ['03', 'Plan', 'Turn evidence into scoped, policy-bound actions.'],
  ['04', 'Verify', 'Run checks in an isolated sandbox before writes.'],
  ['05', 'Approve', 'Put the exact plan and blast radius in front of a human.'],
  ['06', 'Execute', 'Run only narrow, approved tools against exact targets.'],
  ['07', 'Prove', 'Re-scan every identifier and publish the audit trail.'],
];
const features: [LucideIcon, string, string][] = [
  [Database, 'Data discovery', 'Find customer data across PostgreSQL, S3, support tools, analytics, and internal systems.'],
  [Network, 'Identity graph', 'Resolve customer IDs, emails, UUIDs, billing IDs, support IDs, and storage references.'],
  [ShieldCheck, 'Dependency analysis', 'Understand what depends on what before deleting anything.'],
  [FileCheck2, 'Sandbox verification', 'Simulate destructive actions before production execution.'],
  [Terminal, 'Controlled execution', 'The LLM proposes structured actions. Scoped tools enforce them.'],
  [UserCheck, 'Human approval', 'No irreversible production action executes without explicit approval.'],
];

export default function LandingPage(){
  const [open,setOpen]=useState(false);
  return <div className="landing-page">
    <nav className="landing-nav"><Link to="/" className="landing-logo"><span>⌁</span> EraseOps</Link><div className={`landing-links ${open?'open':''}`}><a href="#product" onClick={()=>setOpen(false)}>Product</a><a href="#how" onClick={()=>setOpen(false)}>How it works</a><a href="#security" onClick={()=>setOpen(false)}>Security</a><a href="#integrations" onClick={()=>setOpen(false)}>Integrations</a><a href="#use-cases" onClick={()=>setOpen(false)}>Use cases</a><div className="mobile-links"><a href="#docs">Docs</a><a href="#demo">Request demo</a></div></div><div className="landing-actions"><a className="landing-muted" href="#docs">Docs</a><Link className="landing-console" to="/console"><Terminal size={15}/> Console</Link><button className="landing-menu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button></div></nav>
    <main>
      <section className="landing-hero"><div className="hero-gridline"/><div className="landing-kicker"><span/> AUTONOMOUS DATA DELETION / CONTROL PLANE</div><h1>Erase data.<br/><i>Keep control.</i></h1><p className="landing-lede">EraseOps discovers customer data across your stack, maps dependencies, verifies deletion plans in a sandbox, pauses for human approval, and proves the data is gone.</p><div className="landing-hero-actions"><Link className="landing-primary" to="/console">Open Console <ArrowRight size={16}/></Link><a className="landing-secondary" href="#how">See how it works <ArrowRight size={16}/></a></div><div className="landing-trust"><span><Check/> No unrestricted production access</span><span><Check/> No blind deletion</span><span><Check/> No unverified actions</span></div></section>
      <section className="preview-section" id="product"><div className="section-eyebrow">THE CONTROL PLANE</div><div className="preview-window"><div className="preview-sidebar"><div className="preview-brand">⌁ <span>EraseOps</span></div>{['Overview','Requests','Approvals','Systems','Policies','Audit'].map((x,i)=><div className={i===0?'preview-nav active':'preview-nav'} key={x}><span className="preview-nav-icon"/> {x}</div>)}<div className="preview-env">SANDBOX<br/><b>All systems nominal</b></div></div><div className="preview-main"><div className="preview-top"><span>REQUEST / 8F2C</span><b>AWAITING HUMAN APPROVAL</b></div><h2>Deletion request <em>CUST-1042</em></h2><div className="preview-progress">{['Discovery','Dependencies','Plan','Sandbox','Approval','Execution','Verification'].map((x,i)=><div key={x} className={i<4?'complete':i===4?'current':''}><span>{i<4?'✓':i+1}</span>{x}</div>)}</div><div className="preview-columns"><div><div className="preview-label">DISCOVERED FOOTPRINT</div><div className="preview-stat">8 <small>resources across 2 systems</small></div><div className="preview-lines"><span>PostgreSQL <b>6 resources</b></span><span>AWS S3 <b>2 objects</b></span><span>Shared resources <b className="yellow">review</b></span></div></div><div className="preview-approval"><div className="preview-label">SAFETY GATE</div><ShieldCheck size={25}/><strong>Plan verified.<br/>Approval required.</strong><small>Execution remains locked until a human approves this exact plan.</small><Link to="/console">Review request <ArrowRight size={14}/></Link></div></div><DependencyPreview/></div></div></section>
      <section className="landing-section" id="how"><div className="section-eyebrow">HOW IT WORKS</div><h2 className="landing-heading">Evidence before<br/><i>action.</i></h2><WorkflowVisualization/><div className="steps-grid">{steps.map(([n,title,copy])=><article key={n}><span className="step-number">{n}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
      <section className="landing-section feature-section" id="security"><div className="section-eyebrow">BUILT FOR THE MOMENT THAT MATTERS</div><h2 className="landing-heading">A deletion system<br/><i>you can interrogate.</i></h2><div className="feature-grid">{features.map(([Icon,title,copy])=>{const Component=Icon as typeof ShieldCheck;return <article key={title}><Component/><h3>{title}</h3><p>{copy}</p></article>})}</div></section>
      <section className="landing-cta"><div className="section-eyebrow">READY WHEN YOU ARE</div><h2>Make erasure<br/><i>provable.</i></h2><p>Start with a read-only investigation. Keep every irreversible action behind evidence and approval.</p><Link className="landing-primary" to="/console">Open the Console <ArrowRight size={16}/></Link></section>
    </main><footer className="landing-footer"><Link to="/" className="landing-logo"><span>⌁</span> EraseOps</Link><span>Autonomous data deletion with human control.</span><span>© 2026 EraseOps</span></footer>
  </div>
}

function DependencyPreview(){return <div className="dependency-preview"><div className="preview-label">DEPENDENCY MAP / BLAST RADIUS</div><div className="dependency-canvas"><svg viewBox="0 0 680 150" role="img" aria-label="Customer dependency graph"><path className="graph-line safe-line" d="M92 75 C170 75 185 32 265 32 S350 75 420 75"/><path className="graph-line warn-line" d="M92 75 C170 75 185 118 265 118 S350 75 420 75"/><path className="graph-line delete-line" d="M420 75 C500 75 520 35 600 35"/><path className="graph-line retain-line" d="M420 75 C500 75 520 115 600 115"/><GraphNode x={65} y={75} label="CUST-1042" tone="root"/><GraphNode x={245} y={32} label="orders × 3" tone="delete"/><GraphNode x={245} y={118} label="profile" tone="delete"/><GraphNode x={400} y={75} label="identity graph" tone="safe"/><GraphNode x={580} y={35} label="S3 × 2" tone="delete"/><GraphNode x={580} y={115} label="invoices × 2" tone="retain"/></svg></div><div className="graph-legend"><span><i className="graph-dot delete"/> delete</span><span><i className="graph-dot retain"/> retain</span><span><i className="graph-dot safe"/> verified path</span></div></div>}
function GraphNode({x,y,label,tone}:{x:number;y:number;label:string;tone:string}){return <g className={`graph-node ${tone}`}><circle cx={x} cy={y} r={tone==='root'?18:14}/><text x={x} y={y+32} textAnchor="middle">{label}</text></g>}
function WorkflowVisualization(){return <div className="workflow-visual"><div className="workflow-caption"><span>LIVE CONTROL PATH</span><b>read-only → approved → proven</b></div><svg viewBox="0 0 1120 250" role="img" aria-label="EraseOps evidence workflow from systems through approval to proof"><defs><linearGradient id="flow" x1="0" x2="1"><stop stopColor="#63d6b6" stopOpacity=".15"/><stop offset=".5" stopColor="#63d6b6"/><stop offset="1" stopColor="#dcb56b"/></linearGradient><filter id="glow"><feGaussianBlur stdDeviation="3" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><path className="workflow-track" d="M66 125 H1054"/><path className="workflow-flow" d="M66 125 H1054"/><path className="workflow-branch" d="M170 125 C170 72 225 55 280 55 H390"/><path className="workflow-branch" d="M170 125 C170 178 225 195 280 195 H390"/><circle className="workflow-pulse" cx="66" cy="125" r="4"><animate attributeName="cx" values="66;1054" dur="6s" repeatCount="indefinite"/></circle><WorkflowNode x={66} y={125} label="REQUEST" tone="root"/><WorkflowNode x={280} y={55} label="POSTGRES" tone="source"/><WorkflowNode x={280} y={195} label="S3 / SYSTEMS" tone="source"/><WorkflowNode x={465} y={125} label="EVIDENCE" tone="evidence"/><WorkflowNode x={690} y={125} label="SANDBOX" tone="verify"/><WorkflowNode x={870} y={125} label="APPROVAL" tone="review"/><WorkflowNode x={1054} y={125} label="PROOF" tone="proof"/></svg><div className="workflow-tags"><span>identity resolution</span><span>dependency graph</span><span>blast radius</span><span>audit chain</span></div></div>}
function WorkflowNode({x,y,label,tone}:{x:number;y:number;label:string;tone:string}){return <g className={`workflow-node ${tone}`} filter={tone==='root'?'url(#glow)':undefined}><circle cx={x} cy={y} r={tone==='root'?17:13}/><text x={x} y={y+34} textAnchor="middle">{label}</text></g>}
