import {describe, it, expect} from 'vitest';
import {MinioAdapter, PostgresAdapter} from './adapters.js';
import {MockPostgresConnector} from './index.js';

const hash = 'a'.repeat(64);

describe('connector adapters', () => {
  it('uses parameterized PostgreSQL discovery and classification', async () => { let sql = ''; const adapter = new PostgresAdapter({query: async s => { sql = s; return {rows: [{table_name: 'customers', record_count: 1}, {table_name: 'addresses', record_count: 2}]}; }}); const result = await adapter.discover('CUST-1042'); expect(sql).toContain('$1'); expect(result[0].classification).toBe('anonymize'); expect(result[1].classification).toBe('deletable'); });
  it('inspects foreign-key dependencies from the discovered footprint', async () => { const adapter = new PostgresAdapter({query: async sql => sql.includes('eraseops_customer_footprint') ? {rows: [{table_name: 'payments', record_count: 1}, {table_name: 'order_items', record_count: 2}]} : {rows: []} }); await expect(adapter.inspectDependencies('CUST-1042')).resolves.toEqual([{source: 'pg:payments:CUST-1042', target: 'pg:orders:CUST-1042', relationshipType: 'foreign key', constraintType: 'foreign_key', required: true, risk: 'high'}, {source: 'pg:order_items:CUST-1042', target: 'pg:orders:CUST-1042', relationshipType: 'foreign key', constraintType: 'foreign_key', required: true, risk: 'low'}]); });
  it('previews only allowlisted structured actions', async () => { const adapter = new PostgresAdapter({query: async () => ({rows: []})}); await expect(adapter.previewAction({id: 'a', system: 'PostgreSQL', resource: 'orders', actionType: 'delete', selector: 'customer_id = $1', reason: 'test', recordCount: 1, reversible: false, risk: 'high', dependencies: [], verification: 'rescan'})).resolves.toMatchObject({safe: false}); });
  it('gates PostgreSQL deletion on approval, hash, and table allowlist', async () => { let sql = ''; const adapter = new PostgresAdapter({query: async s => { sql = s; return {rows: [{affected: 1}]}; }}); await expect(adapter.deleteCustomerRecords('CUST-1042', 'customers', false, hash, hash)).rejects.toThrow('Human approval'); await expect(adapter.deleteCustomerRecords('CUST-1042', 'customers', true, hash, 'b'.repeat(64))).rejects.toThrow('Plan hash'); await expect(adapter.deleteCustomerRecords('CUST-1042', 'unknown', true, hash, hash)).rejects.toThrow('not allowlisted'); expect(await adapter.deleteCustomerRecords('CUST-1042', 'customers', true, hash, hash)).toEqual({deleted: 1}); expect(sql).toContain('$1'); });
  it('anonymizes only through the approved parameterized path', async () => { let sql = ''; const adapter = new PostgresAdapter({query: async s => { sql = s; return {rows: [{affected: 2}]}; }}); await expect(adapter.anonymizeCustomerRecords('CUST-1042', false, hash, hash)).rejects.toThrow('Human approval'); expect(await adapter.anonymizeCustomerRecords('CUST-1042', true, hash, hash, 'support_messages')).toEqual({anonymized: 1}); expect(sql).toContain('UPDATE support_messages'); expect(sql).toContain('$1'); });
  it('executes with explicit customer identity and exact plan hash', async () => { const adapter = new PostgresAdapter({query: async () => ({rows: [{affected: 1}]})}); const result = await adapter.executeForCustomer('CUST-1042', {id: 'a', system: 'PostgreSQL', resource: 'addresses', actionType: 'delete', selector: 'customer_id = $1', reason: 'approved', recordCount: 1, reversible: false, risk: 'high', dependencies: [], verification: 'rescan'}, hash, {approved: true, authoritativePlanHash: hash}); expect(result.affectedRecords).toBe(1); });
  it('exports a parameterized database snapshot through the backup writer', async () => { const writes: Array<{bucket:string;key:string;body:string}> = []; const adapter = new PostgresAdapter({query: async sql => sql.includes('eraseops_customer_footprint') ? {rows: [{table_name: 'customers', record_count: 1}]} : {rows: [{payload: [{id: 'redacted-in-memory'}]}]}}, {put: async (bucket, key, body) => { writes.push({bucket, key, body}); }}); const result = await adapter.backupCustomerData('CUST-1042', 'request-1'); expect(result.artifacts).toEqual(['request-1/database.json']); expect(result.resourceEvidence?.[0].records).toBe(1); expect(writes[0].bucket).toBe('eraseops-backups'); expect(writes[0].key).toBe('request-1/database.json'); expect(writes[0].body).toContain('request-1'); });
  it('refuses non-allowlisted MinIO buckets', async () => { const adapter = new MinioAdapter({list: async () => [], copy: async () => {}, delete: async () => {}}, ['customer-uploads']); await expect(adapter.backup('private-bucket', 'x/', 'eraseops-backups/CUST-1042/')).rejects.toThrow('not allowlisted'); });
  it('constrains backup copies to a normalized EraserOps namespace', async () => { const copied: string[] = []; const adapter = new MinioAdapter({list: async () => ['CUST-1042/avatar.png'], copy: async (source, target) => { copied.push(`${source}->${target}`); }, delete: async () => {}}, ['customer-uploads']); await expect(adapter.backup('customer-uploads', 'CUST-1042/', 'unsafe/')).rejects.toThrow('eraseops-backups'); expect(await adapter.backup('customer-uploads', 'CUST-1042/', 'eraseops-backups/CUST-1042/')).toEqual({copied: 1}); expect(copied).toEqual(['customer-uploads/CUST-1042/avatar.png->eraseops-backups/CUST-1042/CUST-1042/avatar.png']); });
  it('rejects traversal-like backup object keys', async () => { const adapter = new MinioAdapter({list: async () => ['CUST-1042/../other-customer.txt'], copy: async () => {}, delete: async () => {}}, ['customer-uploads']); await expect(adapter.backup('customer-uploads', 'CUST-1042/', 'eraseops-backups/CUST-1042/')).rejects.toThrow('path traversal'); });
  it('verifies only remaining allowlisted objects', async () => { const adapter = new MinioAdapter({list: async () => [], copy: async () => {}, delete: async () => {}}, ['customer-uploads']); expect((await adapter.verify('CUST-1042')).verified).toBe(true); });
  it('returns an empty footprint for a customer the systems have never seen', async () => { const connector = new MockPostgresConnector(); await expect(connector.discoverCustomerData('CUST-9999', {demoMode: true, allowlistedHosts: ['postgres'], allowlistedBuckets: ['customer-uploads', 'support-attachments', 'exports']})).resolves.toEqual([]); await expect(connector.discoverCustomerData('9999', {demoMode: true, allowlistedHosts: ['postgres'], allowlistedBuckets: []})).rejects.toThrow('Invalid customer ID'); });
  it('gates MinIO deletion on approval, exact plan hash, and allowlisted keys', async () => { const deleted: string[] = []; const adapter = new MinioAdapter({list: async () => ['CUST-1042/avatar.png', 'CUST-1042/id.pdf'], copy: async () => {}, delete: async key => { deleted.push(key); }}, ['customer-uploads']); await expect(adapter.deleteCustomerObjects('CUST-1042', false, hash, hash)).rejects.toThrow('Human approval'); await expect(adapter.deleteCustomerObjects('CUST-1042', true, hash, 'b'.repeat(64))).rejects.toThrow('Plan hash'); expect(await adapter.deleteCustomerObjects('CUST-1042', true, hash, hash)).toEqual({deleted: 2}); expect(deleted).toEqual(['customer-uploads/CUST-1042/avatar.png', 'customer-uploads/CUST-1042/id.pdf']); });
});

describe('connector capability contract', () => {
  it('derives cross-customer dependencies from the data, not from the customer ID', async () => {
    const connector = new MockPostgresConnector();
    const shared = (await connector.inspectDependencies('CUST-9001')).filter(dependency => dependency.constraintType === 'business');
    expect(shared.map(dependency => dependency.source).sort()).toEqual(['pg:organization_members:CUST-9002', 'pg:organization_members:CUST-9003']);
    expect(shared.every(dependency => dependency.target === 'pg:organizations:CUST-9001' && dependency.risk === 'high')).toBe(true);
    const solo = await connector.inspectDependencies('CUST-1042');
    expect(solo.some(dependency => dependency.constraintType === 'business')).toBe(false);
    expect(solo).toContainEqual(expect.objectContaining({source: 'pg:payments:CUST-1042', target: 'pg:orders:CUST-1042', constraintType: 'foreign_key'}));
    expect(solo).toContainEqual(expect.objectContaining({source: 'pg:orders:CUST-1042', target: 'policy:orders', constraintType: 'retention'}));
  });
});

describe('multi-bucket MinIO discovery', () => { it('scans all configured customer buckets and uses the export key prefix', async () => { const calls: string[] = []; const adapter = new MinioAdapter({list: async (bucket, prefix) => { calls.push(`${bucket}:${prefix}`); return [`${prefix}object`]; }, copy: async () => {}, delete: async () => {}}, ['customer-uploads', 'support-attachments', 'exports']); const assets = await adapter.discover('CUST-1042'); expect(assets).toHaveLength(3); expect(calls).toEqual(['customer-uploads:CUST-1042/', 'support-attachments:CUST-1042/', 'exports:CUST-1042-']); }); });
