import {describe, it, expect} from 'vitest';
import {makeWorkflow} from './server.js';
import {workflowResponseSchema} from '../../../packages/shared/src/index.js';

describe('API workflow service', () => {
  it('matches the shared response contract', async () => { const workflow: any = await makeWorkflow({customerId: 'CUST-1042', reason: 'response contract validation', dryRun: false}); expect(workflowResponseSchema.safeParse(workflow).success).toBe(true); });
  it('discovers the seeded multi-system footprint and derives its blast radius', async () => { const workflow: any = await makeWorkflow({customerId: 'CUST-1042', reason: 'footprint count validation', dryRun: false}); expect(workflow.assets).toHaveLength(14); expect(workflow.assets.filter((asset: any) => asset.system === 'PostgreSQL')).toHaveLength(11); expect(workflow.assets.filter((asset: any) => asset.system === 'MinIO')).toHaveLength(3); expect(workflow.blastRadius).toEqual({systems: 2, records: 16, retained: 4, anonymized: 3, deletable: 9}); expect(workflow.backup.resources).toHaveLength(15); expect(workflow.backup.resources.filter((resource: any) => resource.kind === 'object').map((resource: any) => resource.resource)).toContain('minio:customer-uploads/CUST-1042/id-document.txt'); expect(workflow.backup.resources.every((resource: any) => resource.checksum.length > 16)).toBe(true); expect(workflow.events.find((event: any) => event.stage === 'backup')?.details.connectorBackups).toHaveLength(2); });
  it('persists dry-run mode', async () => { const workflow: any = await makeWorkflow({customerId: 'CUST-1042', reason: 'dry run validation request', dryRun: true}); expect(workflow.dryRun).toBe(true); expect(workflow.stage).toBe('approval'); });
  it('blocks unsafe and backup failure scenarios before approval', async () => { const unsafe: any = await makeWorkflow({customerId: 'CUST-9001', reason: 'cross customer dependency validation', dryRun: false}); const backup: any = await makeWorkflow({customerId: 'CUST-7001', reason: 'backup failure validation', dryRun: false}); expect(unsafe.status).toBe('blocked'); expect(unsafe.stage).toBe('sandbox'); expect(backup.status).toBe('blocked'); expect(backup.stage).toBe('backup'); });
  it('creates an ordered, hash-linked audit trail', async () => { const workflow: any = await makeWorkflow({customerId: 'CUST-1042', reason: 'audit chain validation request', dryRun: false}); expect(workflow.events.length).toBeGreaterThan(5); for (let i = 0; i < workflow.events.length; i++) { expect(workflow.events[i].sequence).toBe(i + 1); expect(workflow.events[i].previousHash).toBe(i === 0 ? 'GENESIS' : workflow.events[i - 1].eventHash); expect(workflow.events[i].eventHash).toHaveLength(64); } });
});
